// "Demo University" — the fictional dataset as a SEPARATE school id (MULTI_SCHOOL_DESIGN §1): fictional
// professors on the real UIUC catalog, generated by scripts/seed-demo.ts into data/raw/demo/demo/. It is
// never mixed with a real school's data; whether it ships is decided by the SCHOOLS env allowlist.
import type { SchoolConfig } from './types';

/** The six subjects the seed generates (SPEC 6.5). */
export const DEMO_SUBJECTS: readonly string[] = ['CS', 'ECE', 'MATH', 'PHYS', 'STAT', 'CHEM'];

export const DEMO: SchoolConfig = {
  id: 'demo',
  name: 'Demo University',
  shortName: 'DEMO',
  timezone: 'America/Chicago',
  mode: 'demo',
  currentTerm: '2026-fa',
  subjects: [...DEMO_SUBJECTS],
  sources: {
    grades: { kind: 'demo-grades' },
    schedule: { kind: 'demo-schedule' },
    reviews: { kind: 'demo-reviews' },
  },
  seatStatusAvailable: true, // the fictional schedule carries open / waitlist / closed
  gradeBuckets: 'plus-minus',
  gradeValueKind: 'counts',
  attribution: {
    grades: 'Fictional demo data: invented professors, reviews and sections on the UIUC course catalog. No real person is described.',
    schedule: 'Fictional demo schedule (seat status generated by the seed).',
  },
  configDir: 'data/config/uiuc', // course priors, departments and the collision guard come from the UIUC catalog
};
