import { MIN_REVIEWS_RANKED, PROMPT_VERSION } from '@/lib/domain/constants';
import { SELECT_CAP, SELECT_PER_BUCKET, REVIEW_TEXT_MAX_CHARS } from '@/lib/ai/selectReviews';
import { SUMMARY_LIMITS } from '@/lib/ai/schema';
import { FormulaBlock } from './FormulaBlock';

export interface AiSectionProps {
  model: string;
  claudeCount: number;
  extractiveCount: number;
  /** Summaries from the OpenAI-compatible provider (Groq by default). */
  llmCount?: number;
  llmProvider?: string;
  llmModel?: string;
  /** Model ids actually present in summaries.json with counts (shown when more than one). */
  llmModels?: readonly { model: string; count: number }[];
}

const SCHEMA_TEXT = `SummarySchema = z.object({
  verdict:           z.string().max(${SUMMARY_LIMITS.verdict}),
  teachingStyle:     z.array(z.string().max(${SUMMARY_LIMITS.teachingStylePhrase})).min(2).max(4),
  strengths:         z.array(z.string().max(${SUMMARY_LIMITS.strength})).min(2).max(4),
  watchOuts:         z.array(z.string().max(${SUMMARY_LIMITS.watchOut})).min(1).max(3),
  bestFor:           z.string().max(${SUMMARY_LIMITS.bestFor}),
  workload:          z.enum(['light', 'moderate', 'heavy']),
  format:            z.enum(['lecture-heavy', 'discussion', 'project-based', 'mixed']),
  confidence:        z.enum(['low', 'medium', 'high']),   // overwritten from review count after parse
  evidenceReviewIds: z.array(z.string()).min(1).max(${SUMMARY_LIMITS.evidenceMax}),
})`;

/** SPEC 3.6 `#ai`: model, schema, review selection, fallback and validation. */
export function AiSection({ model, claudeCount, extractiveCount, llmCount = 0, llmProvider = 'Groq', llmModel = 'openai/gpt-oss-20b', llmModels = [] }: AiSectionProps) {
  const modelLabel = llmModels.length > 1 ? llmModels.map((m) => `${m.model} ×${m.count}`).join(', ') : (llmModels[0]?.model ?? llmModel);
  return (
    <>
      <p>
        Each professor with at least {MIN_REVIEWS_RANKED} reviews gets a short structured summary. In this build{' '}
        <strong>{claudeCount}</strong> {claudeCount === 1 ? 'summary was' : 'summaries were'} written by Claude (
        <code>{model}</code>), <strong>{llmCount}</strong> by {llmProvider} (<code>{modelLabel}</code>, an OpenAI-compatible free-tier provider) and <strong>{extractiveCount}</strong> by the deterministic extractive fallback. The source
        pill on every panel says which one you are reading.
      </p>
      <ul className="list-disc space-y-1 pl-5">
        <li>
          <strong>Precomputed, not live by default.</strong> Models are called by <code>scripts/precompute-summaries.ts</code> (and by the summary route only when <code>SUMMARY_ON_DEMAND=1</code>);
          the deployed app and its API routes never hold an API key. Summaries are committed to{' '}
          <code>data/processed/uiuc/summaries.json</code> keyed by an input hash, so a re-seeded dataset invalidates them.
        </li>
        <li>
          <strong>Review selection is deterministic:</strong> the union of the {SELECT_PER_BUCKET} most recent, the{' '}
          {SELECT_PER_BUCKET} most helpful and the {SELECT_PER_BUCKET} lowest-rated reviews, de-duplicated, capped at{' '}
          {SELECT_CAP}, each text truncated to {REVIEW_TEXT_MAX_CHARS} characters. Including the harshest reviews on purpose
          keeps the summary balanced by construction.
        </li>
        <li>
          <strong>Structured output.</strong> The call uses the Anthropic SDK’s <code>messages.parse</code> with a zod output
          format (below), a short <code>max_tokens</code> budget and low effort. Review text is wrapped in{' '}
          <code>&lt;review&gt;</code> tags and the system prompt (version {PROMPT_VERSION}) instructs the model to treat it
          strictly as data, to invent no numbers, and to avoid personal or protected-attribute commentary.
        </li>
        <li>
          <strong>Validation.</strong> The output is parsed with the schema; every <code>evidenceReviewIds</code> entry must be
          one of the reviews the model was actually shown, or the whole output is discarded. <code>confidence</code> is
          overwritten from the review count and the <strong>grading note is always generated by code</strong> from the
          grade aggregates, so the model can never state a GPA.
        </li>
        <li>
          <strong>Fallback.</strong> No key, a refusal, a rate limit that outlasts the retries, or a validation failure all
          produce the extractive summary: top-scoring review sentences and vibe-tag phrases assembled into the same
          schema. Same input → same bytes, so it is snapshot-tested.
        </li>
        <li>
          <strong>“Why this?”</strong> on the detail page lists the evidence review ids as anchors into the review list, so
          every claim can be traced to a review you can read.
        </li>
      </ul>
      <FormulaBlock title="Structured output schema (src/lib/ai/schema.ts)" formula={SCHEMA_TEXT} />
    </>
  );
}

export default AiSection;
