import type { Meta } from '@/lib/domain/types';
import { formatNumber } from '@/lib/utils/format';

export const GPA_DATASET_URL = 'https://github.com/wadefagen/datasets';
export const GPA_DATASET_CSV_URL = 'https://raw.githubusercontent.com/wadefagen/datasets/main/gpa/uiuc-gpa-dataset.csv';
export const COURSE_EXPLORER_URL = 'https://courses.illinois.edu/cisapp/explorer/schedule';

export interface SourcesSectionProps {
  meta: Pick<Meta, 'mode' | 'seed' | 'sources' | 'seatsFetchedAt'>;
  timezone: string;
}

function stamp(iso: string, timezone: string): string {
  try {
    return new Intl.DateTimeFormat('en-US', { timeZone: timezone, dateStyle: 'medium', timeStyle: 'short' }).format(new Date(iso));
  } catch {
    return iso;
  }
}

/** SPEC 3.6 `#sources`: the three upstreams, their licenses, and what this build actually loaded. */
export function SourcesSection({ meta, timezone }: SourcesSectionProps) {
  const demo = meta.mode === 'demo';
  return (
    <>
      <dl className="space-y-4">
        <div>
          <dt className="font-semibold text-ink">Grades — UIUC GPA dataset</dt>
          <dd>
            <a href={GPA_DATASET_URL} rel="noopener noreferrer" target="_blank">wadefagen/datasets</a>, published under the{' '}
            <strong>MIT license</strong>. One row is one (term, course, section type, primary instructor) aggregate of
            letter grades from 2010 through the most recent released term, as the university releases it under FOIA. It is
            the source of every course title, every course-level grade curve and — in live mode — every per-instructor
            grade row. Attribution: “GPA data from the UIUC GPA dataset by Wade Fagen-Ulmschneider (MIT).”
          </dd>
        </div>
        <div>
          <dt className="font-semibold text-ink">Schedule — UIUC Course Explorer</dt>
          <dd>
            <a href={COURSE_EXPLORER_URL} rel="noopener noreferrer" target="_blank">courses.illinois.edu</a>, a public XML API
            with no license asserted (attribution: “Data from the University of Illinois Course Explorer”). It lists
            sections, meeting times, rooms and instructors per term. <strong>Seat availability is not exposed</strong> by
            the public API: it reports whether a section is active, not whether it has open seats, so in live mode the
            filter reads “Offered this term” instead of “Open seats only”. Demo mode carries fictional seat states so the
            feature can be shown.
          </dd>
        </div>
        <div>
          <dt className="font-semibold text-ink">Reviews</dt>
          <dd>
            {demo ? (
              <>
                In this build every review is <strong>fictional</strong>, generated by the seed script (see the next
                section). No review-site data was fetched.
              </>
            ) : (
              <>
                Live mode can read reviews through an <em>opt-in</em> RateMyProfessors adapter (
                <code>REVIEW_SOURCE=rmp</code>, <code>RMP_ENABLED=1</code>). It uses an unofficial endpoint, is disabled by
                default, is never run in CI, and its output is never committed; the operator running it is responsible
                for complying with that site’s terms of service.
              </>
            )}{' '}
            The pipeline refuses to combine <em>real</em> instructors with <em>fictional</em> reviews: <code>DATA_MODE=live</code>{' '}
            with the demo review source is a hard error.
          </dd>
        </div>
      </dl>
      <h3 className="text-base font-semibold text-ink">What this build loaded</h3>
      <div className="overflow-x-auto rounded-lg border border-border">
        <table className="w-full min-w-[36rem] border-collapse text-left text-sm">
          <caption className="sr-only">Sources recorded in meta.json for this build</caption>
          <thead className="bg-surface-sunken text-xs uppercase tracking-wide text-ink-faint">
            <tr>
              <th scope="col" className="px-3 py-2">Adapter</th>
              <th scope="col" className="px-3 py-2">Label</th>
              <th scope="col" className="px-3 py-2">License</th>
              <th scope="col" className="px-3 py-2 text-right">Records</th>
              <th scope="col" className="px-3 py-2">Fetched</th>
            </tr>
          </thead>
          <tbody>
            {meta.sources.map((s) => (
              <tr key={s.id} className="border-t border-border">
                <td className="px-3 py-2 font-mono text-xs text-ink">{s.id}</td>
                <td className="px-3 py-2 text-ink-muted">
                  {s.url ? <a href={s.url} rel="noopener noreferrer" target="_blank">{s.label}</a> : s.label}
                </td>
                <td className="px-3 py-2 text-ink-muted">{s.license ?? 'none asserted'}</td>
                <td className="px-3 py-2 text-right tabular-nums text-ink-muted">{formatNumber(s.recordCount)}</td>
                <td className="px-3 py-2 text-ink-muted">{stamp(s.fetchedAt, timezone)}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      <p className="text-xs text-ink-faint">
        Seat snapshot taken {stamp(meta.seatsFetchedAt, timezone)} ({timezone}).
        {demo && meta.seed !== null ? ` Demo seed ${meta.seed}.` : ''}
      </p>
    </>
  );
}

export default SourcesSection;
