import { MIN_GRADED_N, MIN_REVIEWS_RANKED } from '@/lib/domain/constants';
import { GPA_DATASET_URL } from './SourcesSection';

/** SPEC 3.6 `#demo` — the fictional-data statement, verbatim. */
export const FICTIONAL_DATA_STATEMENT =
  'All professors, reviews, per-instructor grade rows and sections in demo mode are fictional and generated by `scripts/seed-demo.ts` (seed 20260903). Course titles and course-level grade shapes derive from the public UIUC GPA dataset. Generated names are re-rolled if they collide with any real instructor in that dataset.';

/** Render the statement with the backticked path as <code>, keeping the text itself verbatim. */
function Verbatim({ text }: { text: string }) {
  const parts = text.split('`');
  return (
    <>
      {parts.map((p, i) => (i % 2 === 1 ? <code key={i}>{p}</code> : <span key={i}>{p}</span>))}
    </>
  );
}

export function WhatSection({ schoolShortName }: { schoolShortName: string }) {
  return (
    <>
      <p>
        ProfPeek answers one registration-week question: <strong>which professor should I actually take?</strong> It joins
        three things that normally live on three different tabs — the official grade distribution each instructor gave,
        what students said about them, and which of their sections are still open this term — and ranks the professors
        in a subject with the rules described on this page.
      </p>
      <p>
        It is a portfolio project, not a {schoolShortName} service. Nothing here is endorsed by the university. Rankings
        are one input to a decision, and the tooltips are written so a first-year can see what each number is and is
        not saying.
      </p>
    </>
  );
}

export function DemoSection({ mode, edgeCases }: { mode: 'demo' | 'live'; edgeCases: readonly string[] }) {
  return (
    <>
      <p className="rounded-lg border border-demo/40 bg-demo-soft px-4 py-3 text-ink">
        <Verbatim text={FICTIONAL_DATA_STATEMENT} />
      </p>
      <p>
        Why: the join between grade rows and reviews is by <em>name</em>. If the reviews were fabricated but the names
        were real, a wrong or unlucky match would attribute invented opinions to a real person. So demo mode fabricates
        the people too, and the pipeline refuses to combine real instructors with fictional reviews. Every demo page
        carries the “DEMO DATA — fictional professors &amp; reviews” badge in the header, and every fictional professor
        is captioned as such.
      </p>
      <p>
        What is real in demo mode: the subject and course catalogue, course titles, course-level GPA shapes and typical
        section sizes (all derived from the public dataset), and the parsers, matcher and scoring — the demo grade file is
        written in the dataset’s exact 23-column CSV shape so the real parser runs end to end.
      </p>
      {mode === 'demo' && edgeCases.length > 0 ? (
        <details className="rounded-lg border border-border bg-surface-raised">
          <summary className="cursor-pointer px-4 py-2 text-sm font-medium text-ink">
            Deliberate edge cases planted by the seed ({edgeCases.length})
          </summary>
          <ul className="list-disc space-y-1 px-4 pb-3 pl-9 text-sm">
            {edgeCases.map((e) => (
              <li key={e}>{e}</li>
            ))}
          </ul>
        </details>
      ) : null}
    </>
  );
}

export function LimitationsSection({ seatStatusAvailable }: { seatStatusAvailable: boolean }) {
  return (
    <ul className="list-disc space-y-2 pl-5">
      <li>
        <strong>Grade rows are aggregates, not sections.</strong> The dataset publishes one row per term, course, section
        type and primary instructor, so co-taught courses credit only the listed primary instructor, and rows under{' '}
        {MIN_GRADED_N} graded students are hidden to protect privacy and avoid noise.
      </li>
      <li>
        <strong>Grades lag the schedule.</strong> The newest term in the dataset is usually a semester or two behind the
        term you are registering for; new instructors show “New — no grade data yet” and rank on reviews alone.
      </li>
      <li>
        <strong>Reviews are self-selected.</strong> Students who feel strongly write more; shrinkage and the{' '}
        {MIN_REVIEWS_RANKED}-review floor soften this but cannot remove it. Read the critical count next to every quote.
      </li>
      <li>
        <strong>Name matching is conservative, not perfect.</strong> Ambiguous strings become separate grades-only entries
        rather than guesses, so a professor’s record can be split across two rows when the dataset only gives an initial.
        The match report below lists every decision.
      </li>
      <li>
        <strong>{seatStatusAvailable ? 'Seat status is a snapshot.' : 'Seat status is not available.'}</strong>{' '}
        {seatStatusAvailable
          ? 'It is refreshed when the data is rebuilt, not live; the term pill shows the timestamp and turns amber when it is stale.'
          : 'The public schedule API says whether a section is offered, not whether it has seats.'}
      </li>
      <li>
        <strong>One school.</strong> Only UIUC ships today. The repository and adapter interfaces are multi-school by
        design, but every threshold on this page was tuned on one dataset.
      </li>
      <li>
        <strong>AI summaries are summaries.</strong> They paraphrase the selected reviews under a strict schema with
        validated evidence ids, but they are still generated text; use the “Why this?” links.
      </li>
    </ul>
  );
}

export function PrivacySection() {
  return (
    <>
      <p>
        <strong>No accounts; picks live in your browser.</strong> There is no sign-up, no login and no server-side user
        data. Your shortlist (“My picks”) and your last-chosen school are stored in <code>localStorage</code> on your
        device and never sent anywhere; share links carry the picks in the URL instead. The site sets no tracking cookies
        and loads no third-party analytics.
      </p>
      <p>
        The repository stores no real person’s name in demo data. The only trace of real instructors is a list of
        truncated name hashes used to make sure generated names never collide with a real one (
        <code>data/config/uiuc/real-instructor-keys.json</code>).
      </p>
    </>
  );
}

export function LicensingSection() {
  return (
    <ul className="list-disc space-y-2 pl-5">
      <li>
        <strong>This project</strong> — source code and the fictional demo dataset — is released under the{' '}
        <a href="https://opensource.org/licenses/MIT" rel="noopener noreferrer" target="_blank">MIT License</a>.
      </li>
      <li>
        <strong>UIUC GPA dataset</strong> — <a href={GPA_DATASET_URL} rel="noopener noreferrer" target="_blank">wadefagen/datasets</a>,
        MIT License. Copyright the dataset author; the underlying grade records are public university data.
      </li>
      <li>
        <strong>UIUC Course Explorer</strong> — public API, no license asserted; used with attribution (“Data from the
        University of Illinois Course Explorer”). Nothing fetched from it is redistributed except the processed
        section list for the term shown.
      </li>
      <li>
        <strong>Review sites</strong> — no third-party review content is included in this repository. The optional live
        adapter is off by default and its output is never committed.
      </li>
    </ul>
  );
}
