// Review grammar, part 3 (SPEC 6.5): course clauses ({course} placeholder), weakness clauses and
// advice. Weakness clauses lean on the negative lexicon so low-rated reviews read as low-rated.

export const COURSE_CLAUSES: readonly string[] = [
  'I took {course} last year.',
  'This was for {course}.',
  'Had this professor for {course}.',
  'Took {course} as a requirement for my major.',
  '{course} is a tough course to begin with.',
  'I was in the {course} section that met in the morning.',
  'Took {course} during a heavy semester.',
  'This review is for {course}.',
  '{course} was my first class in the department.',
  'I took {course} with about two hundred other students.',
  'Context: {course}, large lecture section.',
  'Took {course} online during the summer.',
  'My {course} section was small, which helped.',
  '{course} is required, so most of us had to be there.',
  'Second attempt at {course}, and this time it stuck.',
  'I took {course} as an elective.',
  'Signed up for {course} on a friend\'s recommendation.',
  'This was {course}, the evening section.',
  'I took {course} and the follow-up course with the same professor.',
  'Review for the {course} discussion and lecture combined.',
];

export const WEAKNESS_CLAUSES: readonly string[] = [
  'The grading felt inconsistent between TAs.',
  'Office hours were always packed and hard to get into.',
  'Feedback on assignments came back weeks late.',
  'The slides are dense and sometimes hard to read.',
  'Lectures occasionally ran over time.',
  'The exams were harder than the homework suggested.',
  'Some topics were rushed at the end of the semester.',
  'Announcements went out at odd hours with short notice.',
  'The project instructions were vague at first.',
  'Not much partial credit on exams.',
  'The pace picked up too much before the final.',
  'The textbook edition kept changing, which was annoying.',
  'The course website was confusing to navigate.',
  'Group projects were hard to coordinate with the schedule.',
  'Practice exams did not always match the real ones.',
  'Late policy is strict with no exceptions.',
  'Some lectures repeated the reading almost word for word.',
  'The autograder was picky and unforgiving.',
  'It took a long time to get exam grades back.',
  'The curve was smaller than people expected.',
  'A few homework problems were unclear and never clarified.',
  'The discussion sections were disorganized compared to lecture.',
  'Attendance policy felt a bit strict for a large lecture.',
  'Hard to hear in the back of the room without the mic.',
  'The exams were long and most people did not finish.',
  'Not much review before the midterm.',
  'Sometimes answers in office hours contradicted the slides.',
  'The weekly quizzes added a lot of pressure.',
  'The final was heavily weighted, which was stressful.',
  'Several assignments were released late and due on time anyway.',
  'The lecture recordings were sometimes missing.',
  'Regrade requests took forever.',
  'The pace was uneven from week to week.',
  'The homework was much longer than advertised.',
  'The exam room was changed the night before.',
  'The rubric for the project was posted after the deadline.',
  'A lot of the lecture content assumed prior knowledge we did not have.',
  'Difficult to get individual help in a class this size.',
  'The syllabus was vague about how grades were computed.',
  'Extra credit was promised but never materialized.',
];

export const ADVICE_CLAUSES: readonly string[] = [
  'Go to office hours early and often.',
  'Do the practice problems; they are basically the exam.',
  'Start the homework the day it is assigned.',
  'Read the textbook before lecture and everything makes sense.',
  'Form a study group in the first week.',
  'Sit in the front and ask questions.',
  'Do not skip lecture, even when the notes are posted.',
  'Review the notes the same day; the material compounds.',
  'Use the discussion sections — the TAs are excellent.',
  'Take the quizzes seriously, they add up.',
  'Learn the material as you go instead of cramming.',
  'Ask for help the moment you feel lost.',
  'Redo the old exams under time pressure.',
  'Keep a running list of questions for office hours.',
  'Watch the recordings if you miss anything.',
  'Budget more time than you think for the project.',
  'Pay attention to the examples worked in class.',
  'Do every optional problem; they show up later.',
  'Read the feedback on your homework carefully.',
  'Get the textbook early and skim the first chapters.',
  'Do not rely on the curve; earn the points.',
  'Show up to every review session.',
  'Talk to the professor after class; it is worth it.',
  'Make a formula sheet even if you cannot use it on the exam.',
  'Pair up with someone who took the prerequisite recently.',
  'Treat the homework like exam practice.',
  'Print the slides and annotate them during lecture.',
  'Start studying for the final two weeks out.',
  'Take good notes; the exams test understanding, not memory.',
  'Use the posted solutions to check your reasoning, not to copy.',
];
