// Review grammar, part 1 (SPEC 6.5): openers by quality band and closers. Fragments are complete
// sentences; the composer joins them with single spaces. No real people are referenced anywhere.

export type QualityBand = 'low' | 'mid' | 'high';

export function qualityBand(quality: number): QualityBand {
  if (quality <= 2) return 'low';
  if (quality >= 4) return 'high';
  return 'mid';
}

export const OPENERS: Readonly<Record<QualityBand, readonly string[]>> = {
  high: [
    'Honestly one of the best professors I have had here.',
    'Take this class with this professor if you possibly can.',
    'Great professor, would take again in a heartbeat.',
    'I learned more in this course than in any other this year.',
    'Genuinely cares whether students understand the material.',
    'Fantastic lecturer and an even better mentor in office hours.',
    'This class changed how I think about the subject.',
    'Easily a five out of five, no notes.',
    'Clear, kind, and fair — everything you want in a professor.',
    'I looked forward to every single lecture, which never happens.',
    'Best course of my semester by a wide margin.',
    'If you get the chance, take this section.',
    'I recommend this professor to everyone in my major.',
    'Made a notoriously tough subject feel completely doable.',
    'Absolutely loved this class from week one.',
    'You can tell this professor actually enjoys teaching.',
    'Outstanding teacher who respects students and their time.',
    'This is what a well-run course looks like.',
    'One of the most engaging instructors in the department.',
    'I would sign up for anything this professor teaches.',
  ],
  mid: [
    'Solid professor overall, with a few rough edges.',
    'Decent class, nothing amazing but nothing terrible either.',
    'Mixed feelings about this one.',
    'A perfectly fine course if you keep up with the work.',
    'Good professor, average course structure.',
    'Not bad, though it depends a lot on how you learn.',
    'Middle of the road compared to others in the department.',
    'You get out of this class what you put into it.',
    'Reasonable professor, somewhat uneven semester.',
    'Fine overall; some weeks were great and some dragged.',
    'Competent lecturer, but the course could be organized better.',
    'It was okay — I learned the material but it took effort.',
    'A fair class that never quite clicked for me.',
    'Knows the subject well, teaching style is hit or miss.',
    'Good intentions, inconsistent execution.',
    'Neither the best nor the worst class I have taken here.',
    'Worth taking if the schedule works, not worth rearranging your life for.',
    'Pretty standard experience for this department.',
    'I have no strong complaints and no strong praise.',
    'Average in most ways, above average in a couple.',
  ],
  low: [
    'I really struggled to get anything out of this class.',
    'Would not recommend this section to anyone.',
    'Frustrating semester from start to finish.',
    'This course was a mess and the professor did not help.',
    'Avoid if you have any other option.',
    'Hard to follow and harder to get help from.',
    'I taught myself this class from the textbook.',
    'One of my least favorite courses so far.',
    'The lectures did not prepare us for anything on the exams.',
    'Lots of confusion and very little guidance.',
    'I finished the class knowing less than I expected to.',
    'Not a good experience, and I tried to make it work.',
    'Disappointing, especially given how important this course is.',
    'I dreaded going to lecture most weeks.',
    'Expect to rely heavily on your classmates to get through it.',
    'The grading felt arbitrary and the feedback was minimal.',
    'Could have been a great course; it was not.',
    'Too many issues to list in one review.',
    'I would take this course again only with a different instructor.',
    'Rough. Just rough.',
  ],
};

export const CLOSERS: readonly string[] = [
  'Overall I would take it again.',
  'Would recommend to anyone in the major.',
  'Definitely worth it in the end.',
  'Glad I took it.',
  'Ten out of ten would recommend.',
  'One of the good ones.',
  'Solid pick if it fits your schedule.',
  'Recommend with minor reservations.',
  'Fine, but go in with realistic expectations.',
  'Take it if you have to; you will survive.',
  'Not bad, not great.',
  'It grows on you by the end of the semester.',
  'Manageable if you stay on top of things.',
  'Your mileage may vary.',
  'Could be better, could be worse.',
  'Would not take again.',
  'Look for another section if you can.',
  'Not recommended unless it is required.',
  'I do not plan on taking anything else with this professor.',
  'Save yourself the stress.',
  'Learned a lot despite everything.',
  'The material is great even when the delivery is not.',
  'Ended up being one of my favorites.',
  'Wish every class ran this smoothly.',
  'Good luck, and go to office hours.',
  'You have been warned.',
  'Do the work and you will be fine.',
  'Really glad this was my first course in the subject.',
  'Would happily be a TA for this class.',
  'That is all I have to say.',
];
