// Review grammar, part 2 (SPEC 6.5): one clause list per VibeTag. Every clause contains a phrase the
// SPEC 8.9 lexicon can match on word boundaries ("clear lectures", "curve", "weekly problem sets", ...),
// so vibe tags and the extractive summarizer visibly work on the demo data.
import type { VibeTag } from '@/lib/domain/types';

export const TAG_CLAUSES: Readonly<Record<VibeTag, readonly string[]>> = {
  'clear-lectures': [
    'The lectures are incredibly clear and build on each other logically.',
    'Explains clearly, step by step, without skipping the hard parts.',
    'Clear lectures with worked examples every single time.',
    'Very clear explanations even for the trickiest topics.',
    'Explains things clearly and checks that we are following.',
    'Easy to follow lectures — I rarely had to rewatch anything.',
    'Breaks down complicated ideas into clear, digestible pieces.',
    'Clear and well structured lectures from day one.',
    'Every lecture had a clear goal and we actually reached it.',
    'Explains concepts clearly and connects them to the homework.',
  ],
  engaging: [
    'Super engaging lecturer who keeps the whole room awake.',
    'Engaging, funny, and genuinely enthusiastic about the material.',
    'The lectures are engaging enough that attendance felt optional but everyone came.',
    'Very engaging teaching style with lots of interaction.',
    'Makes the material interesting even at 8 AM.',
    'Passionate and engaging; you can feel the enthusiasm.',
    'Engaging discussions instead of a lecture monologue.',
    'Interesting lectures that go beyond the slides.',
    'Keeps things engaging with demos and live examples.',
    'Enthusiastic and entertaining without dumbing anything down.',
  ],
  caring: [
    'Genuinely cares about students and it shows.',
    'Caring and approachable — office hours were a highlight.',
    'Cares about students learning, not just about grades.',
    'Very approachable and always willing to help after class.',
    'Really cares whether you understand and follows up if you do not.',
    'Kind, patient, and supportive when I fell behind.',
    'Actually remembers your name and cares about how you are doing.',
    'Helpful in office hours and quick to respond to email.',
    'Supportive of students who were struggling, no judgment.',
    'You can tell this professor cares about every student in the room.',
  ],
  'fair-grading': [
    'Grading is fair and the rubric is posted ahead of time.',
    'Fair grading with clear expectations for every assignment.',
    'Exams are fair and reflect what was taught.',
    'Fair grader who explains exactly where points were lost.',
    'Very fair exams — no trick questions.',
    'Grades fairly and gives useful feedback on every problem set.',
    'Reasonable grading; partial credit is generous and consistent.',
    'Fair and transparent grading policy from the start.',
    'The tests are fair if you did the practice problems.',
    'Fair grading, fair deadlines, fair professor.',
  ],
  'curves-generously': [
    'There is a generous curve at the end of the semester.',
    'Curves generously so do not panic after the first midterm.',
    'The final grade was curved up quite a bit.',
    'Bumps grades at the end if you are close to the line.',
    'Generous grading overall and a curve on every exam.',
    'Curved the midterm by a lot after the class average tanked.',
    'Grades generously; effort on homework really pays off.',
    'The curve saved a lot of people, including me.',
    'Expect a curve — the raw averages look scary but the final grades are fine.',
    'Very generous with the curve and with extra credit.',
  ],
  'great-notes': [
    'Great notes posted after every lecture.',
    'The lecture notes are excellent and basically a textbook.',
    'Posts detailed notes so you can actually review later.',
    'Great slides and notes that make studying for exams easy.',
    'The notes are so thorough that the textbook is optional.',
    'Provides excellent notes and practice problems with solutions.',
    'Well organized notes that follow the lectures exactly.',
    'Detailed notes and recorded lectures — perfect for review.',
    'Amazing notes, seriously the best resource in the class.',
    'The posted notes are clear and complete; use them.',
  ],
  'heavy-homework': [
    'There is so much homework in this class.',
    'Weekly problem sets that easily take ten hours each.',
    'Heavy workload — lots of homework every single week.',
    'Tons of assignments; plan your semester around it.',
    'Lots of homework, but it does prepare you for the exams.',
    'The homework load is heavy and relentless.',
    'Expect weekly problem sets plus a project on top.',
    'Heavy workload compared to other courses at this level.',
    'So much homework that the class felt like a part-time job.',
    'Assignments are long and frequent; start them early.',
  ],
  'hard-exams': [
    'The exams are hard — much harder than the homework.',
    'Hard exams with a tight time limit.',
    'Difficult tests that go beyond what was covered in lecture.',
    'Exams are brutal; the average was below sixty.',
    'Hard midterms, harder final.',
    'The tests are difficult and the questions are long.',
    'Expect hard exams that require real understanding, not memorization.',
    'Exams are tough but the practice exams help.',
    'Very difficult exams; study the old ones religiously.',
    'Hard exams with almost no partial credit.',
  ],
  'fast-paced': [
    'Fast paced — we covered a chapter a week.',
    'The course moves fast, so do not fall behind.',
    'Very fast paced lectures that assume you did the reading.',
    'Moves quickly through the material with little review.',
    'Fast paced but doable if you keep up.',
    'The pace is relentless; miss one lecture and you are lost.',
    'Covers a lot of material very quickly.',
    'Quick pace, dense lectures, and no slowing down before exams.',
    'Fast paced class that rewards students who prepare ahead.',
    'Moves fast, especially in the second half of the semester.',
  ],
  disorganized: [
    'The course is disorganized and deadlines change constantly.',
    'Disorganized lectures that jump around between topics.',
    'Very disorganized — assignments were posted late more than once.',
    'The course site was a mess and announcements contradicted each other.',
    'Disorganized grading; some assignments were never returned.',
    'Lectures felt unprepared and unorganized most weeks.',
    'Scattered and disorganized; hard to know what to study.',
    'Poorly organized course with confusing instructions.',
    'Disorganized to the point where the TAs were guessing too.',
    'The schedule changed so often that the syllabus was useless.',
  ],
  'strict-attendance': [
    'Attendance is mandatory and counts toward your grade.',
    'Strict attendance policy with clicker questions every lecture.',
    'Takes attendance every day; missing class costs points.',
    'Mandatory attendance, even for the 8 AM section.',
    'Strict about attendance and about being on time.',
    'Attendance is required and there are pop quizzes.',
    'You have to show up — participation is a big part of the grade.',
    'Attendance is mandatory with no excused absences without paperwork.',
    'Strict attendance; the clicker points add up quickly.',
    'Do not skip: attendance is tracked and graded.',
  ],
  'must-read-textbook': [
    'You must read the textbook to keep up.',
    'The textbook is required and the exams pull from it directly.',
    'Read the textbook — lectures only cover half the material.',
    'Must read the textbook before each lecture or you will be lost.',
    'The book is essential; the slides alone are not enough.',
    'Heavy reading load from the textbook every week.',
    'Exam questions come straight from the textbook readings.',
    'You need the textbook; lectures assume you have read it.',
    'Reading the textbook is mandatory, not optional, in this class.',
    'The textbook does most of the teaching, honestly.',
  ],
};

/** 20 RMP-style source tags; the seed picks 1–3 conditioned on the professor's styleTags. */
export const SOURCE_TAGS: readonly string[] = [
  'Amazing lectures', 'Caring', 'Clear grading criteria', 'Gives good feedback', 'Respected',
  'Inspirational', 'Accessible outside class', 'Lecture heavy', 'Graded by few things', 'Test heavy',
  'Lots of homework', 'Tough grader', 'Get ready to read', 'Skip class? You won\'t pass', 'Participation matters',
  'Group projects', 'Beware of pop quizzes', 'So many papers', 'Extra credit', 'Hilarious',
];

/** Which source tags a style tag makes likelier (indices into SOURCE_TAGS by name). */
export const SOURCE_TAGS_BY_STYLE: Readonly<Record<VibeTag, readonly string[]>> = {
  'clear-lectures': ['Amazing lectures', 'Clear grading criteria', 'Lecture heavy'],
  engaging: ['Amazing lectures', 'Inspirational', 'Hilarious'],
  caring: ['Caring', 'Accessible outside class', 'Gives good feedback'],
  'fair-grading': ['Clear grading criteria', 'Gives good feedback', 'Respected'],
  'curves-generously': ['Extra credit', 'Graded by few things', 'Respected'],
  'great-notes': ['Amazing lectures', 'Lecture heavy', 'Clear grading criteria'],
  'heavy-homework': ['Lots of homework', 'So many papers', 'Group projects'],
  'hard-exams': ['Test heavy', 'Tough grader', 'Graded by few things'],
  'fast-paced': ['Lecture heavy', 'Get ready to read', 'Tough grader'],
  disorganized: ['So many papers', 'Group projects', 'Test heavy'],
  'strict-attendance': ['Skip class? You won\'t pass', 'Participation matters', 'Beware of pop quizzes'],
  'must-read-textbook': ['Get ready to read', 'Test heavy', 'Lecture heavy'],
};
